export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';

export const JWT_ACCESS_TOKEN_EXPIRATION = '1h';

export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';

export const JWT_REFRESH_TOKEN_EXPIRATION = '60d';
