const CONTROLLER_ROUTE = '/auth';

const COOKIE_MAX_EXPIRATION_DAYS = 400;

const SESSION_TOKEN_LOCK_KEY = 'lock:session_token';

const SESSION_TOKEN_LOCK_RELEASE_TIME = 5000;

export {
  CONTROLLER_ROUTE,
  COOKIE_MAX_EXPIRATION_DAYS,
  SESSION_TOKEN_LOCK_KEY,
  SESSION_TOKEN_LOCK_RELEASE_TIME,
};
